name: Cleanup Artifacts

on:
  workflow_run:
    workflows: ["delete all artifacts"] # Replace with your workflow name
    types:
      - completed
  push:
    branches:
      - "master"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete All Artifacts
        run: |
          gh run list -L 100 --json databaseId --jq '.[].databaseId' | xargs -n1 gh run delete -f
